export const caseStudies = [
  {
    slug: 'ecommerce-platform',
    title: 'Plataforma E-commerce Multi-vendor',
    shortDescription: 'Marketplace B2B para proveedores industriales con pagos Stripe Connect y panel de administración.',
    thumbnail: '/images/case-study-ecommerce.svg',
    tags: ['Next.js', 'PostgreSQL', 'Stripe Connect', 'TypeScript'],
    featured: true,
    problem: 'Cliente necesitaba migrar de WooCommerce a una solución headless que soportara múltiples vendedores, comisiones automáticas y escalabilidad a 10k+ productos.',
    approach: 'Arquitectura headless con Next.js 14 (App Router) + PostgreSQL + Stripe Connect para marketplace. Separación clara entre frontend (Next.js) y backend (API Routes + Prisma).',
    techStack: ['Next.js 14', 'TypeScript', 'PostgreSQL', 'Prisma ORM', 'Stripe Connect', 'Tailwind CSS', 'Vercel'],
    keyDecisions: [
      {
        title: 'Next.js App Router vs Pages Router',
        context: 'El cliente necesitaba SEO fuerte y rendimiento en mobile.',
        decision: 'App Router con Server Components para SEO y RSC para datos estáticos.',
        tradeoffs: 'Curva de aprendizaje del equipo, pero mejor Core Web Vitals y SEO nativo.',
      },
      {
        title: 'Stripe Connect vs Custom Billing',
        context: 'Marketplace multi-vendor con comisiones variables.',
        decision: 'Stripe Connect Standard para onboarding rápido y compliance PCI.',
        tradeoffs: 'Comisiones de Stripe (2.9% + 30¢) vs desarrollo custom (6+ meses).',
      },
      {
        title: 'Prisma vs Raw SQL',
        context: 'Equipo pequeño, iteración rápida, tipado end-to-end.',
        decision: 'Prisma para type-safety end-to-end y migraciones versionadas.',
        tradeoffs: 'Overhead de 15-20ms por query vs raw SQL, pero cero runtime type errors.',
      },
    ],
    outcome: {
      metrics: [
        { label: 'Tiempo de carga', value: '< 1.2s', description: 'LCP en mobile' },
        { label: 'Conversión checkout', value: '+34%', description: 'vs WooCommerce anterior' },
        { label: 'Tiempo desarrollo', value: '3 meses', description: 'vs 6+ estimado custom' },
      ],
      testimonial: 'La migración fue impecable. El equipo entendió el negocio y entregó antes de plazo.',
      client: 'Industrial Supply Co.',
    },
    liveUrl: 'https://industrial-supply.pe',
    repoUrl: 'https://github.com/asahel/ecommerce-platform',
  },
  {
    slug: 'saas-dashboard',
    title: 'Dashboard SaaS para Gestión de Proyectos',
    shortDescription: 'Dashboard colaborativo en tiempo real con WebSockets, drag-and-drop y analytics.',
    thumbnail: '/images/case-study-dashboard.svg',
    tags: ['Next.js', 'Socket.io', 'PostgreSQL', 'Tailwind'],
    featured: false,
    problem: 'Startup necesitaba dashboard para equipos remotos con colaboración en tiempo real, kanban, gantt y métricas de productividad.',
    approach: 'Next.js + Socket.io para real-time + PostgreSQL + Prisma. Arquitectura de microservicios ligeros: API Gateway + WebSocket Server + Background Workers (BullMQ).',
    techStack: ['Next.js 14', 'TypeScript', 'Socket.io', 'PostgreSQL', 'Prisma', 'BullMQ', 'Redis', 'Tailwind', 'Vercel + Railway'],
    keyDecisions: [
      {
        title: 'WebSockets vs Server-Sent Events',
        context: 'Bidireccionalidad necesaria para edición colaborativa.',
        decision: 'Socket.io con fallback automático a polling.',
        tradeoffs: 'Más complejidad en servidor vs SSE simple, pero necesario para edición concurrente.',
      },
      {
        title: 'Arquitectura Monolito Modular vs Microservicios',
        context: 'Equipo de 3 devs, velocidad de iteración crítica.',
        decision: 'Monolito modular con separación clara de dominios (auth, projects, realtime, analytics).',
        tradeoffs: 'Despliegue único simple vs escalabilidad independiente futura.',
      },
    ],
    outcome: {
      metrics: [
        { label: 'Usuarios concurrentes', value: '500+', description: 'Sin degradación' },
        { label: 'Latencia WebSocket', value: '< 50ms', description: 'P95 global' },
        { label: 'Tiempo desarrollo', value: '4 meses', description: 'MVP a producción' },
      ],
      testimonial: 'El real-time funciona impecable. El equipo técnico entendió los edge cases de concurrencia.',
      client: 'ProjectFlow Inc.',
    },
    liveUrl: 'https://projectflow.io',
    repoUrl: 'https://github.com/asahel/saas-dashboard',
  },
  {
    slug: 'api-integration-platform',
    title: 'Plataforma de Integración API Unificada',
    shortDescription: 'Middleware para conectar ERPs, CRMs y e-commerces con cola de mensajes y retry automático.',
    thumbnail: '/images/case-study-api.svg',
    tags: ['Node.js', 'TypeScript', 'RabbitMQ', 'PostgreSQL', 'OpenAPI'],
    featured: false,
    problem: 'Empresa con 5+ sistemas desconectados (ERP, CRM, Shopify, MercadoLibre, facturación) necesitaba sincronización bidireccional confiable.',
    approach: 'Middleware Node.js + TypeScript + RabbitMQ para cola de mensajes + PostgreSQL para estado + OpenAPI spec generation. Circuit breaker + retry exponencial + dead letter queue.',
    techStack: ['Node.js', 'TypeScript', 'RabbitMQ', 'PostgreSQL', 'Prisma', 'OpenAPI 3.1', 'Docker', 'Kubernetes'],
    keyDecisions: [
      {
        title: 'RabbitMQ vs Kafka',
        context: 'Volumen moderado (<100k msgs/día), necesidad de routing complejo y dead letter.',
        decision: 'RabbitMQ por routing flexible, TTL, DLX nativo y management UI.',
        tradeoffs: 'Kafka mejor para alto throughput, pero overkill para este volumen.',
      },
      {
        title: 'OpenAPI Code Generation vs Manual Clients',
        context: '5+ APIs externas con specs cambiantes.',
        decision: 'Orval para generar clientes TypeScript + Zod schemas desde OpenAPI specs.',
        tradeoffs: 'Setup inicial vs cero drift entre spec y cliente, regeneración automática en CI.',
      },
    ],
    outcome: {
      metrics: [
        { label: 'Uptime', value: '99.97%', description: 'Últimos 12 meses' },
        { label: 'Tiempo sync', value: '< 30s', description: 'End-to-end promedio' },
        { label: 'Errores manuales', value: '-95%', description: 'vs procesos manuales previos' },
      ],
      testimonial: 'Finalmente tenemos visibilidad total de la data. El retry automático salvó miles de transacciones.',
      client: 'Logistics Corp.',
    },
    liveUrl: undefined,
    repoUrl: 'https://github.com/asahel/api-integration-platform',
  },
] as const;